spring.application.name=SpringAuthentication
#spring.security.user.name=admin
#spring.security.user.password=admin

# --- MySQL Database Configuration ---
#?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC optional for
# Connection URL (creates the database automatically if it doesn't exist on some local setups, depending on permissions)
spring.datasource.url=jdbc:mysql://localhost:3306/springsecuritydb
spring.datasource.username=root
spring.datasource.password=huzaifa#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate Properties ---
# 'update' automatically updates your DB schema based on your Java @Entity classes.
# Use 'none' or 'validate' in production!
spring.jpa.hibernate.ddl-auto=update

# Optional: Shows SQL queries in the console (great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=2ee7a13e27ebece68a8761c093f0fa405e9901748d38fb539ff5ce87aa7361ee
application.security.jwt.expiration=1800000
application.security.jwt.refresh-expiration=420000